export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_FETCHING_DATA = "USER_FETCHING_DATA";

export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";
export const USER_SIGNUP_LOADING = "USER_SIGNUP_LOADING";

export const USER_PROFILE_UPDATE_LOADING = "USER_PROFILE_UPDATE_LOADING";
export const USER_PROFILE_UPDATE_ERROR = "USER_PROFILE_UPDATE_ERROR";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";

export const USER_CHANGE_PASSWORD_LOADING = "USER_CHANGE_PASSWORD_LOADING";
export const USER_CHANGE_PASSWORD_ERROR = "USER_CHANGE_PASSWORD_ERROR";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";

export const USER_ADD_BOOK = "USER_ADD_BOOK";
export const USER_ADD_BOOK_LOADING = "USER_ADD_BOOK_LOADING";
export const USER_ADD_BOOK_ERROR = "USER_ADD_BOOK_ERROR";

export const USER_BOOK_DELETE = "USER_BOOK_DELETE";
export const USER_BOOK_DELETE_LOADING = "USER_BOOK_DELETE_LOADING";
export const USER_BOOK_DELETE_ERROR = "USER_BOOK_DELETE_ERROR";

export const USER_FETCH_BOOKS = "USER_FETCH_BOOKS";
export const USER_FETCH_BOOKS_LOADING = "USRE_FETCH_BOOKS_LOADING";
export const USER_FETCH_BOOKS_ERROR = "USER_FETCH_BOOKS_ERROR";

export const USER_TRADE_NEW = "USER_TRADE_NEW";
export const USER_TRADE_NEW_LOADING = "USER_TRADE_NEW_LOADING";
export const USER_TRADE_NEW_ERROR = "USER_TRADE_NEW_ERROR";

export const USER_TRADES_FETCH = "USER_TRADES_FETCH";
export const USER_TRADES_FETCH_LOADING = "USER_TRADES_FETCH_LOADING";

export const USER_TRADE_CHANGE_STATUS = "USER_TRADE_CHANGE_STATUS";

export const USER_TRADE_LOADING = "USER_TRADE_LOADING";

export const USER_TRADES_ERROR = "USER_TRADES_ERROR";

export const USER_TRADE_CANCEL = "USER_TRADE_CANCEL";


export const BOOK_SEARCH = "BOOK_SEARCH";
export const BOOK_SEARCH_LOADING = "BOOK_SEARCH_LOADING";
export const BOOK_SEARCH_SUCCESS = "BOOK_SEARCH_SUCCESS";
export const BOOK_SEARCH_ERROR = "BOOK_SEARCH_ERROR";

export const BOOK_FETCH_BOOKS = "BOOK_FETCH_BOOKS";
export const BOOK_FETCH_BOOKS_LOADING = "BOOK_FETCH_BOOKS_LOADING";
export const BOOK_FETCH_BOOKS_ERROR = "BOOK_FETCH_BOOKS_ERROR";