export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_FETCHING_DATA = "USER_FETCHING_DATA";

export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";
export const USER_SIGNUP_LOADING = "USER_SIGNUP_LOADING";